version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    container_name: MessengerAPI
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./messenger:/messenger"
    env_file:
      - ./messenger/.env
    command: uvicorn messenger.server:app --reload --host 0.0.0.0 --port 8080
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: MessengerDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./messenger/.env

volumes:
  postgresql_data: